apiVersion: v1
kind: Service
metadata:
  name: {{ include "cobalt-strike.fullname" . }}
  labels:
    {{- include "cobalt-strike.labels" . | nindent 4 }}
  {{- if .Values.service.annotations }}
  annotations:
    {{- range $key, $value := $.Values.service.annotations }}
    {{ $key }}: {{ toYaml $value }}
    {{- end }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
{{- if eq .Values.service.type "ClusterIP" }}
  clusterIP: None
{{- end }}
  ports:
  {{- range .Values.service.ports }}
    - port: {{ .port }}
      targetPort: {{ .targetPort }}
      protocol: {{ .protocol }}
      name: {{ .name }}
  {{- end }}
  selector:
    {{- include "cobalt-strike.selectorLabels" . | nindent 4 }}